Repository shlyapos/TrackTor, pull requests merged in 2022-03, with the labels that each got.

#12 added docs folder with er diagram image and drawio src
  docs/images/ER.png
  docs/src/ER.drawio
Labels: documentation

#19 feature/11 init angular app and add material lib
  web-client/.browserslistrc
  web-client/.editorconfig
  web-client/.gitignore
  web-client/README.md
  web-client/angular.json
  web-client/karma.conf.js
  web-client/package-lock.json
  web-client/package.json
  web-client/src/app/app/app-routing.module.ts
  web-client/src/app/app/app.module.ts
  web-client/src/app/app/components/app.component.html
  web-client/src/app/app/components/app.component.less
  web-client/src/app/app/components/app.component.ts
  web-client/src/app/material-proxy/material-proxy.module.ts
  web-client/src/assets/.gitkeep
  web-client/src/environments/environment.prod.ts
  web-client/src/environments/environment.ts
  web-client/src/favicon.ico
  web-client/src/index.html
  web-client/src/main.ts
  web-client/src/polyfills.ts
  web-client/src/styles.less
  web-client/src/test.ts
  web-client/tsconfig.app.json
  web-client/tsconfig.json
  web-client/tsconfig.spec.json
Labels: FrontEnd

#18 Feature/14 project and start page init
  mobile/.gitignore
  mobile/App.ts
  mobile/app.json
  mobile/babel.config.js
  mobile/declaration.d.ts
  mobile/metro.config.js
  mobile/package.json
  mobile/src/App.module.css
  mobile/src/App.tsx
  mobile/src/pages/TrackCreate/TrackCreate.module.css
  mobile/src/pages/TrackCreate/TrackCreatePage.tsx
  mobile/src/pages/TrackCreate/index.tsx
  mobile/src/pages/TrackList/TrackList.module.css
  mobile/src/pages/TrackList/TrackListPage.tsx
  mobile/src/pages/TrackList/index.tsx
  mobile/tsconfig.json
  mobile/tslint.json
  mobile/yarn.lock
Labels: FrontEnd, mobile

#20 removed result checkpoint table from ER / added some fields
  docs/images/ER.png
  docs/src/ER.drawio
Labels: documentation, BackEnd

#21 Feature/17 Создание компонента списка треков
  web-client/package-lock.json
  web-client/package.json
  web-client/src/app/app/app-routing.module.ts
  web-client/src/app/app/app.module.ts
  web-client/src/app/app/components/app.component.html
  web-client/src/app/app/components/app.component.ts
  web-client/src/app/app/index.ts
  web-client/src/app/material-proxy/material-proxy.module.ts
  web-client/src/app/shared/models/left-sidebar.ts
  web-client/src/app/shared/models/track.ts
  web-client/src/app/track/components/left-sidebar/left-sidebar.actions.ts
  web-client/src/app/track/components/left-sidebar/left-sidebar.component.html
  web-client/src/app/track/components/left-sidebar/left-sidebar.component.less
  web-client/src/app/track/components/left-sidebar/left-sidebar.component.ts
  web-client/src/app/track/components/left-sidebar/left-sidebar.reducer.ts
  web-client/src/app/track/components/track-info/track-info.component.html
  web-client/src/app/track/components/track-info/track-info.component.less
  web-client/src/app/track/components/track-info/track-info.component.ts
  web-client/src/app/track/components/track-item/track-item.component.html
  web-client/src/app/track/components/track-item/track-item.component.less
  web-client/src/app/track/components/track-item/track-item.component.ts
  web-client/src/app/track/components/track-list/track-list.component.html
  web-client/src/app/track/components/track-list/track-list.component.less
  web-client/src/app/track/components/track-list/track-list.component.ts
  web-client/src/app/track/components/track-page/track-page.component.html
  web-client/src/app/track/components/track-page/track-page.component.less
  web-client/src/app/track/components/track-page/track-page.component.ts
  web-client/src/app/track/components/track-search/track-search.actions.ts
  web-client/src/app/track/components/track-search/track-search.component.html
  web-client/src/app/track/components/track-search/track-search.component.less
  web-client/src/app/track/components/track-search/track-search.component.ts
  web-client/src/app/track/components/track-search/track-search.reducer.ts
  web-client/src/app/track/track-routing.module.ts
  web-client/src/app/track/track.actions.ts
  web-client/src/app/track/track.module.ts
  web-client/src/app/track/track.reducer.ts
  web-client/src/colors.less
  web-client/src/styles.less
Labels: FrontEnd, Webclient
